def tri(tab):
    # i est le premier indice de la zone non triee,
    # j est le dernier indice de cette zone non triée. 
    # Au debut, la zone non triee est le tableau complet.
    i= ...
    j= ...
    while i != j :
        if tab[i] == 0:
            i= ...
        else :
            valeur = tab[j]
            tab[j] = ...
            ...
            j= ...
    ...
